apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 100xdevs/env-backend
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_PASSWORD
          value: "yourpassword"
