version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=mysecretpassword
  

  user-app: 
    build: 
      network: host
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - postgres
